version: '3.8'
services:
  ocean-market:
    image: oceanenterprise/market:latest
    container_name: ocean-market
    pull_policy: always
    ports:
      - '8008:8008'
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
