version: '3.8'
services:
  ocean-market:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_ENCRYPT_ASSET: ${NEXT_PUBLIC_ENCRYPT_ASSET}
        NEXT_PUBLIC_SSI_WALLET_API: ${NEXT_PUBLIC_SSI_WALLET_API}
        NEXT_PUBLIC_METADATACACHE_URI: ${NEXT_PUBLIC_METADATACACHE_URI}
        NEXT_PUBLIC_PROVIDER_URL: ${NEXT_PUBLIC_PROVIDER_URL}
        NEXT_PUBLIC_IPFS_UNPIN_FILES: ${NEXT_PUBLIC_IPFS_UNPIN_FILES}
        NEXT_PUBLIC_NODE_URI: ${NEXT_PUBLIC_NODE_URI}
        NEXT_PUBLIC_IPFS_GATEWAY: ${NEXT_PUBLIC_IPFS_GATEWAY}
        NEXT_PUBLIC_IPFS_JWT: ${NEXT_PUBLIC_IPFS_JWT}
        NEXT_PUBLIC_SSI_POLICY_SERVER: ${NEXT_PUBLIC_SSI_POLICY_SERVER}
        NEXT_PUBLIC_SSI_DEFAULT_POLICIES_URL: ${NEXT_PUBLIC_SSI_DEFAULT_POLICIES_URL}
        NEXT_PUBLIC_OPA_SERVER_URL: ${NEXT_PUBLIC_OPA_SERVER_URL}
        NEXT_PUBLIC_SSI_ENABLED: ${NEXT_PUBLIC_SSI_ENABLED}
        NEXT_PUBLIC_SHOW_ONBOARDING_MODULE_BY_DEFAULT: ${NEXT_PUBLIC_SHOW_ONBOARDING_MODULE_BY_DEFAULT}
        NEXT_PUBLIC_NODE_URI_INDEXED: ${NEXT_PUBLIC_NODE_URI_INDEXED}
        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
        NEXT_PUBLIC_INFURA_PROJECT_ID: ${NEXT_PUBLIC_INFURA_PROJECT_ID}
        NEXT_PUBLIC_CONSUME_MARKET_FEE: ${NEXT_PUBLIC_CONSUME_MARKET_FEE}
        NEXT_PUBLIC_CONSUME_MARKET_ORDER_FEE: ${NEXT_PUBLIC_CONSUME_MARKET_ORDER_FEE}
        NEXT_PUBLIC_CREDENTIAL_VALIDITY_DURATION: ${NEXT_PUBLIC_CREDENTIAL_VALIDITY_DURATION}
        NEXT_PUBLIC_NODE_URI_MAP: ${NEXT_PUBLIC_NODE_URI_MAP}
        NEXT_PUBLIC_MARKET_FEE_ADDRESS: ${NEXT_PUBLIC_MARKET_FEE_ADDRESS}
        NEXT_PUBLIC_ERC20_ADDRESSES: ${NEXT_PUBLIC_ERC20_ADDRESSES}
    container_name: ocean-market
    ports:
      - '8008:8008'
    environment:
      NODE_ENV: production
    restart: unless-stopped
